### ISSUE TITLE
Forcing a checkout of c0c0a4 on cl-webkit?

### ISSUE THREAD

**Issue by ahungry** [AeroNotix/lispkit#75]
I use Arch Linux and they don't provide a 3.0 or below version of libwebkit2gtk.  The commit c0c0a4 on cl-webkit only supports up to 3.0.so.x, while the latest version of cl-webkit supports up to 4.0.

Is there a reason why this detached head state has to be checked out instead of left in Master branch? (it happens on line 45 of Makefile).

**Comment by Ralt** [comment]
Hi,

Travis is based on ubuntu. On ubuntu, it needs the alpha version (vivid, or 15.04) to download libwebkit2gtk-4.0. It worked fine for a time, then it ended up crashing (because, well, alpha), so we reverted to 3.0. But cl-webkit starts supporting 4.0 after some commit... somewhere after the 2.0 tag. So we could've used it.... but this tag doesn't include some bindings, namely related to webkitinspector. So a specific commit is needed: after this binding, but before the switch to 4.0.

I guess since arch uses libwebkit2gtk-4.0, the PKGBUILD needs some `sed -i 's/git checkout c0c0a4//` Makefile`.

@AeroNotix you're on arch... mind doing it? I couldn't test it.

**Comment by AeroNotix** [comment]
@ahungry @Ralt  done! Thanks for the help!
